new

diff --git a/.local/bin/scripts/uplibpath b/.local/bin/scripts/uplibpath
--- a/.local/bin/scripts/uplibpath
+++ b/.local/bin/scripts/uplibpath
@@ -1,19 +1,20 @@
 #!/bin/sh
-for file in $(find "$1" -type f -name '*.c' -o -name '*.h' -o -name '*.cpp' -o -name '*.hpp'); do
-	olds=$(awk -F'"' '/^[ \t]*#[ \t]*include[ \t/]{1,}"[^"]{1,}"/ {print $2}' $file)
+cd "$1" || return
+for file in $(echo *.c *.h *.cpp *.hpp); do
+	olds=$(awk -F'"' '/^[ \t]*#[ \t]*include[ \t/]{1,}"[^"]{1,}"/ {print $2}' "$file")
 	for old in $olds; do
-		[ -f $old ] && continue
-		old=$(echo $old | sed 's/[\.\/]*//')
+		[ -f "$old" ] && continue
+		old=$(echo "$old" | sed 's/[\.\/]*//')
 		new=$old
 		i=0
 		while :; do
-			if [ -f $new ]; then
-				printf '%s' "$(sed "s|#.*include.*$old.*|#include \"$new\"|" $file)" >$file
+			if [ -f "$new" ]; then
+				printf '%s' "$(sed "s|#.*include.*$old.*|#include \"$new\"|" "$file")" >"$file"
 				echo "Replaced $old to $new in $file"
 				break
 			fi
 			if [ $i -ge 5 ]; then
-				printf "Can't find the correct path for %s after %s iterations\nLast tried path is %s" $old $i $new
+				printf "Can't find the correct path for %s after %s iterations\nLast tried path is %s" "$old" $i "$new"
 				break
 			fi
 			new="../$new"
